config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:create, :new, :show]

  resource :session, only: [:create, :new, :destroy, :show]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new, :index]

  resources :notes, only: [:create, :destroy]
end

app/models/album.rb
class Album < ActiveRecord::Base

  validates :name, :band_id, :category, presence: true

  belongs_to :band

  has_many :tracks, dependent: :destroy
end

app/models/band.rb
class Band < ActiveRecord::Base

  validates :name, presence: true

  has_many :albums, dependent: :destroy
end

app/models/note.rb
class Note < ActiveRecord::Base

  validates :user_id, :track_id, presence: true

  belongs_to :user

  belongs_to :track

end

app/models/track.rb
class Track < ActiveRecord::Base

  validates :name, :album_id, :category, presence: true

  belongs_to :album

  has_many :notes, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_reader :password

  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  has_many :notes, dependent: :destroy

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
    self.save!
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action :require_user

  def new
    @band = Band.find_by_id(params[:id])
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find_by_id(params[:id])
    render :edit
  end

  def update
    @album = Album.find_by_id(params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def show
    @album = Album.find_by_id(params[:id])
    render :show
  end

  def destroy
    @album = Album.find_by_id(params[:id])
    @album.destroy
    redirect_to bands_url
  end

  private

  def album_params
    params.require(:album).permit(:name, :band_id, :category)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def login(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def logout
    current_user.reset_session_token! if current_user
    session[:session_token] = nil
  end

  def logged_in?
    return true if current_user
    false
  end

  def require_no_user
  end

  def require_user
    redirect_to new_session_url unless current_user
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  before_action :require_user

  def index
    @bands = Band.all
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def new
    render :new
  end

  def edit
    @band = Band.find_by_id(params[:id])
    render :edit
  end

  def update
    @band = Band.find_by_id(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def show
    @band = Band.find_by_id(params[:id])
    render :show
  end

  def destroy
    @band = Band.find_by_id(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :require_user

  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    @not.save
    flash[:errors] = @note.errors.full_messages
    render
  end

  def destroy
    @note = Note.find_by_id(params[:id])
    unless note.user_id == current_user.id
      render text: "Can only destroy your own notes"
    else
      track = @note.track
      @note.destroy
      redirect_to track_url(track)
    end
  end

  private

  def note_params
    params.require(:note).permit(:user_id, :track_id, :user_notes)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user.nil?
      flash.now[:errors] = ["Invalid email and/or password"]
      render :new
    else
      login(@user)
      redirect_to bands_url
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

  def show
    @user = User.find_by_id(params[:id])
    render :show
  end

  private

  def session_params
    params.require(:session).permit(:email, :password, :session_token)
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  before_action :require_user

  def new
    @album = Album.find_by_id(params[:id])
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
    @track = Track.find_by_id(params[:id])
    render :edit
  end

  def update
    @track = Track.find_by_id(params[:id])
    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def show
    @track = Track.find_by_id(params[:id])
    render :show
  end

  def destroy
    @track = Track.find_by_id(params[:id])
    @track.destroy
    redirect_to bands_url
  end

  private

  def track_params
    params.require(:track).permit(:name, :album_id, :category, :lyrics)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.new(email: params[:user][:email], password: params[:user][:password])
    if @user.save
      login(@user)
      redirect_to bands_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/edit.html.erb
<h2>Edit your album</h2>
<%= @album.name %>
<br>

<form action="<%= album_url(@album) %>" method="post">
  <input type="hidden" name="_method" value="patch">

  <input type="hidden" name="authenticity_token" value="form_authenticity_token">

  <label for="album_name">Album Name</label>
  <input id="album_name" type="text" name="album[name]" value="<%= @album.name %>">
  <br>

  <label for="band_name">Band Name</label>
  <select id="band_name" name="album[band_id]">
    <% Band.all.each do |band| %>
      <% parent_band = band.id == @album.band_id ? "selected" : ""%>
      <option <%= parent_band %> value="<%= band.id %>" ><%= band.name %></option>
    <% end %>
  </select>
  <br>

  <label for="category">Category</label><br>
  <input type="radio" name="album[category]" value="live" <%= @album.category == "live" ? "checked" : ""  %> >Live<br>
  <input type="radio" name="album[category]" value="studio" <%= @album.category == "studio" ? "checked" : "" %>>Studio<br>

  <input type="submit" value="Save">

</form>

app/views/albums/new.html.erb
<h2>Let's create our own album!</h2>

<form action='/albums' method="post">

  <input type="hidden" name="authenticity_token" value="form_authenticity_token">

  <label for="album_name">Album Name</label>
  <input id="album_name" type="text" name="album[name]">
  <br>

  <label for="band_name">Band</label>
  <select name="album[band_id]" id="band_name">
    <% Band.all.each do |band| %>
      <% if params[:band_id] == band.id  %>
        <option value="<%= band.id %>" selected><%= band.name %></option>
      <% else %>
        <option value="<%= band.id %>"><%= band.name %></option>
      <% end %>
    <% end %>
  </select>
  <br>

  <label for="category">Category</label><br>
  <input id="category" type="radio" name="album[category]" value="live">Live<br>
  <input id="category" type="radio" name="album[category]" value="studio">Studio<br>

  <input type="submit" value="Create My Album">
</form>

app/views/albums/show.html.erb
<header>
  <%= link_to 'Back To All Bands', bands_url, method: :get %>
</header>

<h2> <%= @album.name %>  </h2>

<br>
<b>Tracks</b>
<br>
<br>

<% @album.tracks.each do |track| %>
  <%= link_to track.name, track_url(track) %><br>
<% end %>
<br>
<br>

<b>Links</b>
<br>
<ul>
  <li>
    <%= link_to 'New Track', new_album_track_url(@album), method: :get %>
  </li>
  <li>
    <%= link_to 'Edit Album', edit_album_url(@album), method: :get %>
  </li>
  <li>
    <%= link_to 'Delete Album', album_url(@album), method: :delete %>
  </li>
</ul>

app/views/bands/edit.html.erb
<h2>Edit your band</h2>
<b> <%= @band.name %> </b><br>

<form action=<%= band_url(@band) %> method="post">
  <input type="hidden" name="_method" value="patch">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="band_name">Band Name</label>
  <input id="band_name" type="text" name="band[name]" value="<%= @band.name %>">

  <input type="submit" value="Save">

</form>

app/views/bands/index.html.erb
<h1>All the bands!</h1>

<ul>
  <% @bands.each do |band| %>
    <li>
      <%= link_to band.name, band_url(band) %>
    </li>
  <% end %>
</ul>

<%= button_to 'Create Your Own Band', new_band_url, method: :get %>

app/views/bands/new.html.erb
<h1>Let's create a new Band!</h1>

<form action="/bands" method="post">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="band_name">Band Name</label>
  <input id="band_name" type="text" name="band[name]">

  <input type="submit" value="Create My Band!">
</form>

app/views/bands/show.html.erb
<h2> <%= @band.name %>  </h2>

<b>Albums</b>
<br>
<br>
<% @band.albums.each do |album| %>
  <ul>
    <li>
      <%= link_to album.name, album_url(album) %>
    </li>
  </ul>
<% end %>
<br>

<b>Links</b>
<ul>
  <li>
    <%= link_to 'New Album', new_band_album_url(@band), method: :get %>
  </li>
  <li>
    <%= link_to 'Edit Band', edit_band_url(@band), method: :get%>
  </li>
  <li>
    <%= link_to 'Delete Band', band_url(@band), method: :delete %>
  </li>
  <li>
    <%= link_to 'All Bands', bands_url, method: :get %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<header>
  <% if flash.now[:errors] %>
    <ul>
      <% flash.now[:errors].each do |error| %>
        <li>
          <%= error %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <% if current_user %>
    <p>Logged in as <%= current_user.email %></p>
  <% end %>

</header>

<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user %>
    <%= button_to 'Logout', '/session', method: :delete %>
  <% else %>
    <%= button_to 'Sign Up', '/users/new', method: :get %>
    <%= button_to 'Sign In', '/session/new', method: :get %>
  <% end %>
  <br>

<%= yield %>


</body>
</html>

app/views/notes/_note.html.erb
<b>New Note</b>
<br>


<b>Notes</b>
<br>

<ul>
  <% @track.notes.each do |note| %>
  <li>
    <%= note.user_notes %>
  </li>
  <% end %>
</ul>

app/views/tracks/edit.html.erb
<h2>Edit your track</h2>
<br>
<b><%= @track.name %></b>

<form action=<%= track_url(@track) %>  method="post">
  <input type="hidden" name="_method" value="patch">

  <input type="hidden" name="authenticity_token" value="form_authenticity_token">

  <label for="track_name">Track Name</label>
  <input id="track_name" type="text" name="track[name]" value=<%= @track.name %>>
  <br>

  <label for="album_name">Album Name</label>
  <select id="album_name" name="track[album_id]">
    <% Album.all.each do |album| %>
      <% parent_album = album.id == params[:id] %>
      <option value="<%= album.id %>" <%= parent_album ? "selected" : "" %>><%= album.name %></option>
    <% end %>
  </select>
  <br>

  <label for="category">Category</label><br>
  <input id="category" type="radio" name="track[category]" value="bonus" <%= @track.category == "bonus" ? "checked" : ""  %>>Bonus<br>
  <input id="category" type="radio" name="track[category]" value="regular" <%= @track.category == "regular" ? "checked" : "" %>>Regular<br>

  <textarea name="track[lyrics]" rows="8" cols="40" value=<%= @track.lyrics %>>Lyrics</textarea>

  <input type="submit" value="Save">


</form>

app/views/tracks/new.html.erb
<h2>Let's create a track!</h2>

<form action='/tracks' method="post">

  <input type="hidden" name="authenticity_token" value="form_authenticity_token">

  <label for="track_name">Track Name</label>
  <input id="track_name" type="text" name="track[name]">
  <br>

  <label for="album_name">Album Name</label>
  <select id="album_name" name="track[album_id]">
    <% Album.all.each do |album| %>
      <% parent_album = album.id == params[:id] %>
      <option value="<%= album.id %>" <%= parent_album ? "selected" : "" %>><%= album.name %></option>
    <% end %>
  </select>
  <br>

  <label for="category">Category</label><br>
  <input id="category" type="radio" name="track[category]" value="bonus">Bonus<br>
  <input id="category" type="radio" name="track[category]" value="regular">Regular<br>

  <textarea name="track[lyrics]" rows="8" cols="40">Lyrics</textarea>

  <input type="submit" value="Create My Track">

</form>

app/views/tracks/show.html.erb
<header>
  <%= link_to 'Back To All Bands', bands_url, method: :get %><br>
  <%= link_to 'Back to Album', album_url(@track.album), method: :get %>
</header>

<h2> <%= @track.name %> </h2>

<b>Links</b>
<br>

<ul>
  <li>
    <%= link_to 'Edit Track', edit_track_url(@track), method: :get %>
  </li>
  <li>
    <%= link_to 'Delete Track', track_url(@track), method: :delete %>
  </li>
</ul>

app/views/users/new.html.erb
<h1>Please enter details to sign up</h1>

<form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="Email">Email</label>
  <input id="Email" type="text" name="user[email]">
  <br>

  <label for="Password">Password</label>
  <input id="Password" type="password" name="user[password]">
  <br>

  <input type="submit">

</form>

app/views/users/show.html.erb
<h2>Welcome <%= @user.email %> </h2>